source(here::here("Bring_In_Data.R"))
source(here::here("Jacob_Lasoo_Lib.R"))
library(igraph)

# there appears to be some run to run variability. I did not set a seed for the figures in the paper, but
# the outcomes are similar between runs, with some varibility in whether weak edges are seen
# If you want the output from the run used in the paper please run `load(here::here("archive", "x2022Oct13.RData"))`
set.seed(10034)

## Functions
delete_isolated <- function(G){
  Isolated = which(degree(G) == 0)
  G2 = delete.vertices(G, Isolated)
}

# Debug

# Run calculation. Here we consider only positive edges.
CoefMtx <- xy_common_lasoo(Y = VirMat, X = CyanoEnvMat, ll = 0) # breaks if there are columns with only one zero in CyanoEnvMat

## Processing

EnvNames <- colnames(EnvTransformed)[-1]
CyanoNames <- colnames(CyanoTransformed)[-1]

Edges <- CoefMtx %>% make_edges_table() %>% only_strong_cyano_edges()
Nodes <- make_nodes_table(colnames(VirMat),CyanoNames, EnvNames) %>% only_cyano_nodes()

## Plotting

CVGraph2 <- graph_from_data_frame(d = Edges, directed = FALSE, vertices = Nodes)

CVGraph2_Connected <- delete_isolated(CVGraph2)

plot(CVGraph2_Connected, vertex.size = 20,
     vertex.label.cex = .8,
     edge.label.cex = 0.8,
     edge.label.dist = 1,
     edge.label.color = "black",
     edge.color = adjustcolor(E(CVGraph2_Connected)$color, 0.5)
     )


## Environmental Network
# Here we consider connections to environmental nodes too

EdgesEnv <- CoefMtx %>% make_edges_table() #%>% only_strong_env_edges()
#NodesEnv <- make_nodes_table(colnames(VirMat), colnames(CyanoMat), EnvNames) #%>% no_cyano_nodes()
# Hardcoded devide, which I don't love
NodesEnv <- make_nodes_table(colnames(VirMat), colnames(CyanoEnvMat)[c(1:8)], colnames(CyanoEnvMat)[-c(1:8)])

CVGraphEnv <- graph_from_data_frame(d = EdgesEnv, directed = FALSE)
# not working for now
CVGraphEnv <- graph_from_data_frame(d = EdgesEnv, directed = FALSE, vertices = NodesEnv) %>%
  delete_isolated()

plot(CVGraphEnv, vertex.size = 15)

# the below funcitons are useful if you want to reposition verteces, commented out for now
#tkp <- tkplot(CVGraphEnv, vertex.size = 15)
# 
# tkCoords <- tkplot.getcoords(tkp, norm = FALSE)
# plot(CVGraphEnv, vertex.size = 15, layout = tkCoords)

## As above, but this time, allowing for negative values

# Run calculation
CoefMtx_Neg <- xy_common_lasoo(Y = VirMat, X = CyanoEnvMat, ll = -Inf)

Edges_Neg <- CoefMtx_Neg %>% make_edges_table() %>% only_strong_cyano_edges()


CVGraph2_Neg <- graph_from_data_frame(d = Edges_Neg, directed = FALSE, vertices = Nodes)

CVGraph2_Neg_Connected <- delete_isolated(CVGraph2_Neg)

plot(CVGraph2_Neg_Connected, vertex.size = 20,
     vertex.label.cex = .8,
     edge.label.cex = 0.8,
     edge.label.dist = 1,
     edge.label.color = "black",
     edge.color = adjustcolor(E(CVGraph2_Connected)$color, 0.5))

# tkp2 <- tkplot(CVGraph2_Neg_Connected, vertex.size = 15)
# tkCoords2 <- tkplot.getcoords(tkp2, norm = FALSE)
# plot(CVGraph2_Connected)

## 
# Combine the two networks
# The goal here is to plot both with points in the same place.

# The gui generated by tkplot allows the user to specify the locations of each point
# then those locations are used for the positive only and negative plot

# the hand positioned data is saved in "archive/x2022Oct12.RData"

PNUnion <- union(CVGraph2_Connected, CVGraph2_Neg_Connected)
tkp_union <- tkplot(PNUnion)
tkCoordsUnion <- tkplot.getcoords(tkp_union, norm = FALSE)

# par(mfrow =c(1,2))
# plot(CVGraph2_Connected, layout = tkCoordsUnion)
# plot(CVGraph2_Neg_Connected, layout = tkCoordsUnion)
# # Not quite working. 

UnionCoords <- tibble(Node = names(V(PNUnion)), X = tkCoordsUnion[,1], Y = tkCoordsUnion[,2])

PosV <- tibble(Node = names(V(CVGraph2_Connected)))

PosNegV <- tibble(Node = names(V(CVGraph2_Neg_Connected)))

PosCoords_df <- inner_join(PosV, UnionCoords)

PosNegCoords_df <- inner_join(PosNegV, UnionCoords)

PosCoords_mtx <- PosCoords_df[,c(2,3)] %>% as.matrix()

PosNegCoords_mtx <- PosNegCoords_df[,c(2,3)] %>% as.matrix()

## save out the combined plot
svg(file = "TwoCyanovirus.svg")
par(mfrow = c(1,2))
plot(CVGraph2_Connected, layout = PosCoords_mtx,
     vertex.size = 25,
     vertex.label.cex = .5,
     edge.label.cex = 0.5,
     edge.label.dist = 1,
     edge.label.color = "black",
     edge.color = adjustcolor(E(CVGraph2_Connected)$color, 0.75)
    )

plot(CVGraph2_Neg_Connected, layout = PosNegCoords_mtx,
     vertex.size = 25,
     vertex.label.cex = .5,
     edge.label.cex = 0.5,
     edge.label.dist = 1,
     edge.label.color = "black",
     edge.color = adjustcolor(E(CVGraph2_Neg_Connected)$color, 0.75)
     )
dev.off()

# save image file
save.image("x2022Nov03.RData")
